/* BEGIN_LEGAL 

Copyright (c) 2021 Intel Corporation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  
END_LEGAL */
/// @file xed-encoder-gen-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_ENCODER_GEN_DEFS_H)
# define XED_ENCODER_GEN_DEFS_H
#define XED_ENCODE_ORDER_MAX_ENTRIES  32
#define XED_ENCODE_ORDER_MAX_OPERANDS 5
#define XED_ENCODE_MAX_FB_PATTERNS 121
#define XED_ENCODE_MAX_EMIT_PATTERNS 199
#define XED_ENCODE_FB_VALUES_TABLE_SIZE 3880
#define XED_ENCODE_MAX_IFORMS 7639
#define XED_ENC_GROUPS 535
#endif
