
/*************************************************************
 *
 *                  DO NOT EDIT THIS FILE!
 *
 * THIS FILE IS AUTOGENERATED BY THE PIN BUILD SYSTEM
 *
 *************************************************************/

#ifndef PIN_VERSION_H
#define PIN_VERSION_H


/*! @ingroup VERSION
 * The Pin major version number.
 */
#define PIN_PRODUCT_VERSION_MAJOR 3

/*! @ingroup VERSION
 * The Pin minor version number.
 */
#define PIN_PRODUCT_VERSION_MINOR 21

/*! @ingroup VERSION
 * The Pin kit build number. This is unique for every Pin kit.
 */
#define PIN_BUILD_NUMBER 98484

/*! @ingroup VERSION
 * The git hash for this Pin build. This is unique for every Pin kit.
 */
#define PIN_COMMIT_HASH "e7cd811fd"

#endif // PIN_VERSION_H
